const triviaData = {
    eu: {
        easy: [
            { q: "What does EU stand for?", options: ["European Union", "Europe United", "Euro Union", "European Unity"], answer: 0 },
            { q: "What currency is used in most EU countries?", options: ["Dollar", "Pound", "Euro", "Franc"], answer: 2 },
            { q: "Which of these is not an EU member?", options: ["France", "Germany", "United Kingdom", "Italy"], answer: 2 },
            { q: "What colors are on the EU flag?", options: ["Red & White", "Blue & Gold", "Green & White", "Black & Yellow"], answer: 1 },
            { q: "Where is the European Parliament primarily located?", options: ["London", "Berlin", "Strasbourg", "Paris"], answer: 2 },
            { q: "How many stars are on the EU flag?", options: ["10", "12", "15", "50"], answer: 1 },
            { q: "Who is the current President of the European Commission? (as of 2024)", options: ["Angela Merkel", "Emmanuel Macron", "Ursula von der Leyen", "Charles Michel"], answer: 2 },
            { q: "Which treaty established the European Union in 1993?", options: ["Treaty of Paris", "Treaty of Rome", "Treaty of Maastricht", "Treaty of Lisbon"], answer: 2 },
            { q: "Which of these countries is in the EU?", options: ["Norway", "Switzerland", "Spain", "Iceland"], answer: 2 },
            { q: "What is the EU's anthem?", options: ["Ode to Joy", "God Save the King", "La Marseillaise", "Star Spangled Banner"], answer: 0 },
            { q: "What year was the Euro introduced as an electronic currency?", options: ["1999", "2000", "2001", "2002"], answer: 0 },
            { q: "Which of the following is NOT an official language of the EU?", options: ["English", "French", "Russian", "German"], answer: 2 },
            { q: "How often are European Parliament elections held?", options: ["Every 3 years", "Every 4 years", "Every 5 years", "Every 6 years"], answer: 2 },
            { q: "What is the main purpose of the EU?", options: ["Military alliance", "Economic and political partnership", "Sports organization", "Cultural exchange program"], answer: 1 },
            { q: "Which country left the EU in 2020?", options: ["France", "Germany", "United Kingdom", "Italy"], answer: 2 }
        ],
        medium: [
            { q: "Which country holds the largest population in the EU?", options: ["France", "Germany", "Italy", "Spain"], answer: 1 },
            { q: "Which institution represents the member states' governments?", options: ["European Commission", "European Parliament", "Council of the European Union", "European Court of Justice"], answer: 2 },
            { q: "When did the Euro officially enter circulation as physical currency?", options: ["1999", "2000", "2002", "2005"], answer: 2 },
            { q: "Which EU country joined most recently (in 2013)?", options: ["Bulgaria", "Romania", "Croatia", "Slovenia"], answer: 2 },
            { q: "How many official languages does the EU have?", options: ["12", "15", "24", "27"], answer: 2 },
            { q: "Which city is known as the de facto capital of the EU?", options: ["Brussels", "Luxembourg City", "Frankfurt", "Strasbourg"], answer: 0 },
            { q: "Which of these countries does NOT use the Euro?", options: ["Austria", "Poland", "Finland", "Ireland"], answer: 1 },
            { q: "What is the Schengen Area?", options: ["A trade agreement", "A zone without internal borders", "An economic union", "A military alliance"], answer: 1 },
            { q: "Which treaty, signed in 2007, forms the current constitutional basis of the EU?", options: ["Treaty of Nice", "Treaty of Amsterdam", "Treaty of Lisbon", "Treaty of Rome"], answer: 2 },
            { q: "Which body proposes new EU legislation?", options: ["European Parliament", "European Commission", "European Council", "European Central Bank"], answer: 1 },
            { q: "Which EU agency is responsible for border and coast guard control?", options: ["Frontex", "Europol", "Eurojust", "EASA"], answer: 0 },
            { q: "What is the total number of EU member states as of 2024?", options: ["25", "27", "28", "30"], answer: 1 },
            { q: "Which country currently uses the Euro but is NOT in the EU?", options: ["Kosovo", "Iceland", "Switzerland", "Serbia"], answer: 0 },
            { q: "What is the motto of the European Union?", options: ["Liberty, Equality, Fraternity", "In God We Trust", "United in Diversity", "Strength Through Unity"], answer: 2 },
            { q: "Where is the European Court of Justice located?", options: ["Brussels", "Strasbourg", "Luxembourg City", "The Hague"], answer: 2 }
        ],
        hard: [
            { q: "Which six countries were the founding members of the ECSC in 1951?", options: ["UK, France, Germany, Italy, Spain, Portugal", "France, West Germany, Italy, Belgium, Netherlands, Luxembourg", "France, Germany, Italy, Austria, Belgium, Netherlands", "Norway, Sweden, Denmark, Finland, Iceland, UK"], answer: 1 },
            { q: "Where is the European Central Bank headquartered?", options: ["Brussels", "Paris", "Frankfurt", "Vienna"], answer: 2 },
            { q: "What was the precursor to the European Union?", options: ["European Economic Community", "European Trade Union", "League of European Nations", "European Monetary System"], answer: 0 },
            { q: "Which Article of the Treaty on European Union outlines the procedure for leaving the EU?", options: ["Article 7", "Article 42", "Article 50", "Article 101"], answer: 2 },
            { q: "Which EU country has the highest GDP per capita?", options: ["Germany", "Ireland", "Luxembourg", "Netherlands"], answer: 2 },
            { q: "How are Members of the European Parliament (MEPs) elected?", options: ["Appointed by national governments", "Elected by national parliaments", "Directly elected by EU citizens", "Appointed by the Commission"], answer: 2 },
            { q: "Which EU program funds educational exchanges?", options: ["Erasmus+", "Horizon Europe", "Copernicus", "Galileo"], answer: 0 },
            { q: "Which country rejected the European Constitution in a 2005 referendum?", options: ["Ireland", "Denmark", "France", "Spain"], answer: 2 },
            { q: "What is the primary role of the European Court of Auditors?", options: ["Drafting laws", "Checking EU funds are collected and used correctly", "Judging human rights cases", "Setting interest rates"], answer: 1 },
            { q: "Which of the following is an EU microstate but NOT an EU member?", options: ["Malta", "Cyprus", "Monaco", "Luxembourg"], answer: 2 },
            { q: "What does the 'QMV' voting system in the EU stand for?", options: ["Qualified Majority Voting", "Quarterly Member Vote", "Quota Margin Voting", "Quick Majority Vote"], answer: 0 },
            { q: "Which EU program is dedicated to environmental and climate action?", options: ["Erasmus+", "LIFE", "Horizon", "Copernicus"], answer: 1 },
            { q: "Who was the 'father' of the Euro currency?", options: ["Jean Monnet", "Robert Schuman", "Jacques Delors", "Helmut Kohl"], answer: 2 },
            { q: "The 'Dublin Regulation' primarily deals with what issue?", options: ["Trade tariffs", "Agricultural subsidies", "Asylum seekers", "Currency exchange"], answer: 2 },
            { q: "Which non-EU country is part of the EU Customs Union?", options: ["Turkey", "Norway", "Switzerland", "Ukraine"], answer: 0 }
        ],
        expert: [
            { q: "The Schuman Declaration, which led to the ECSC, was made on what exact date?", options: ["May 9, 1950", "April 18, 1951", "March 25, 1957", "January 1, 1958"], answer: 0 },
            { q: "Which member state holds an opt-out from the Economic and Monetary Union (Euro)?", options: ["Sweden", "Denmark", "Poland", "Hungary"], answer: 1 },
            { q: "What is the 'Copenhagen Criteria'?", options: ["Environmental standards", "Rules for joining the EU", "Trade tariffs", "Agricultural subsidies"], answer: 1 },
            { q: "In the Council of the EU, what constitutes a 'qualified majority'?", options: ["55% of states representing 65% of the population", "50% of states representing 50% of the population", "75% of states representing 50% of the population", "Unanimity"], answer: 0 },
            { q: "Which non-EU countries are in the EEA (European Economic Area)?", options: ["Switzerland, UK", "Norway, Iceland, Liechtenstein", "Serbia, Montenegro, Albania", "Turkey, Georgia, Ukraine"], answer: 1 },
            { q: "The 'Spitzenkandidat' process refers to the election of which role?", options: ["President of the European Parliament", "President of the European Commission", "High Representative", "President of the European Council"], answer: 1 },
            { q: "Which policy area makes up the largest single part of the EU budget?", options: ["Defense", "Space Exploration", "Common Agricultural Policy (CAP)", "Foreign Aid"], answer: 2 },
            { q: "Which EU body is responsible for foreign and security policy?", options: ["European External Action Service (EEAS)", "Frontex", "Europol", "European Defense Agency"], answer: 0 },
            { q: "The 'Acquis communautaire' refers to what?", options: ["The EU's single market", "The accumulated legislation, legal acts, and court decisions of the EU", "The internal border force", "The common currency mechanism"], answer: 1 },
            { q: "Which treaty introduced the concept of European citizenship?", options: ["Treaty of Rome", "Treaty of Amsterdam", "Treaty of Maastricht", "Single European Act"], answer: 2 },
            { q: "What is the 'ordinary legislative procedure' formerly known as?", options: ["Assent procedure", "Co-decision procedure", "Consultation procedure", "Consent procedure"], answer: 1 },
            { q: "Which EU institution is NOT located in Brussels?", options: ["European Central Bank", "European Commission", "European Council", "Council of the European Union"], answer: 0 },
            { q: "The 'Cassis de Dijon' case established which major EU legal principle?", options: ["Subsidiarity", "Direct effect", "Mutual recognition", "Proportionality"], answer: 2 },
            { q: "Which fund supports the economic development of the EU's poorest regions?", options: ["Cohesion Fund", "European Social Fund", "European Regional Development Fund", "European Solidarity Fund"], answer: 0 },
            { q: "What year was the Single European Act signed?", options: ["1986", "1992", "1997", "2001"], answer: 0 }
        ]
    },
    hungary: {
        easy: [
            { q: "What is the capital of Hungary?", options: ["Budapest", "Debrecen", "Szeged", "Miskolc"], answer: 0 },
            { q: "Who is the current Prime Minister of Hungary? (as of 2024)", options: ["Viktor Orbán", "Katalin Novák", "Péter Magyar", "Ferenc Gyurcsány"], answer: 0 },
            { q: "What is the currency of Hungary?", options: ["Euro", "Hungarian Forint", "Kuna", "Złoty"], answer: 1 },
            { q: "Which major river flows through Budapest?", options: ["Rhine", "Seine", "Danube", "Thames"], answer: 2 },
            { q: "What colors are on the Hungarian flag?", options: ["Red, White, Green", "Black, Red, Gold", "Blue, Yellow, Red", "White, Blue, Red"], answer: 0 },
            { q: "Hungary is located in which region?", options: ["Scandinavia", "Central Europe", "Iberian Peninsula", "British Isles"], answer: 1 },
            { q: "Is Hungary a member of the European Union?", options: ["Yes", "No", "Applying", "Suspended"], answer: 0 },
            { q: "What is the primary language spoken in Hungary?", options: ["English", "German", "Hungarian", "Slavic"], answer: 2 },
            { q: "What type of government does Hungary have?", options: ["Absolute Monarchy", "Parliamentary Republic", "Federal Republic", "Theocracy"], answer: 1 },
            { q: "Which large building is the seat of the National Assembly of Hungary?", options: ["Buda Castle", "Hungarian Parliament Building", "St. Stephen's Basilica", "Fisherman's Bastion"], answer: 1 },
            { q: "What is the traditional Hungarian meat and paprika stew called?", options: ["Schnitzel", "Borscht", "Goulash", "Pierogi"], answer: 2 },
            { q: "What lake is affectionately known as the 'Hungarian Sea'?", options: ["Lake Geneva", "Lake Balaton", "Lake Bled", "Lake Constance"], answer: 1 },
            { q: "Which colorful 3D puzzle was invented by a Hungarian architecture professor?", options: ["Jenga", "Lego", "Rubik's Cube", "Tetris"], answer: 2 },
            { q: "What is the popular, strong Hungarian fruit brandy called?", options: ["Vodka", "Rakija", "Pálinka", "Ouzo"], answer: 2 },
            { q: "What are the colors of the Hungarian flag from top to bottom?", options: ["Red, White, Green", "Green, White, Red", "Blue, Yellow, Red", "White, Blue, Red"], answer: 0 },
            { q: "What is the traditional Hungarian spiced sweet bread called?", options: ["Bejgli", "Flódni", "Dobos torte", "Kürtőskalács"], answer: 3 },
            { q: "Which Hungarian dance is fast and performed at celebrations?", options: ["Waltz", "Csárdás", "Polka", "Tango"], answer: 1 }
        ],
        medium: [
            { q: "When did Hungary join the European Union?", options: ["1999", "2004", "2007", "2013"], answer: 1 },
            { q: "Which political party is currently in power in Hungary? (as of 2024)", options: ["MSZP", "Jobbik", "Fidesz", "Momentum"], answer: 2 },
            { q: "Who is the current President of Hungary? (as of mid-2024)", options: ["Katalin Novák", "Tamás Sulyok", "Viktor Orbán", "János Áder"], answer: 1 },
            { q: "When did the communist regime in Hungary fall?", options: ["1989", "1991", "1980", "1995"], answer: 0 },
            { q: "How many members are in the Hungarian National Assembly (Országgyűlés)?", options: ["199", "386", "450", "120"], answer: 0 },
            { q: "Which famous revolution against Soviet policies took place in Hungary?", options: ["The Velvet Revolution (1989)", "The Prague Spring (1968)", "The Hungarian Revolution of 1956", "The Orange Revolution (2004)"], answer: 2 },
            { q: "Hungary borders how many countries?", options: ["5", "6", "7", "8"], answer: 2 },
            { q: "Which electoral system does Hungary use for its National Assembly?", options: ["Pure Proportional Representation", "Mixed-member majoritarian", "First-past-the-post exclusively", "Single Transferable Vote"], answer: 1 },
            { q: "The Treaty of Trianon, which caused Hungary to lose substantial territory, was signed after which war?", options: ["World War I", "World War II", "The Cold War", "The Austro-Prussian War"], answer: 0 },
            { q: "Which organization did Hungary join in 1999 alongside Poland and the Czech Republic?", options: ["EU", "NATO", "Warsaw Pact", "Eurozone"], answer: 1 },
            { q: "Which cities merged in 1873 to form the capital, Budapest?", options: ["Buda and Pest", "Buda, Pest, and Óbuda", "Budapest and Gödöllő", "Pest and Esztergom"], answer: 1 },
            { q: "What is the second-largest city in Hungary?", options: ["Szeged", "Miskolc", "Pécs", "Debrecen"], answer: 3 },
            { q: "Which famous 19th-century Hungarian composer wrote the 'Hungarian Rhapsodies'?", options: ["Béla Bartók", "Zoltán Kodály", "Franz Liszt", "Johannes Brahms"], answer: 2 },
            { q: "Who is the legendary first King of Hungary, crowned in 1000 AD?", options: ["Matthias Corvinus", "Stephen I", "Louis the Great", "Béla IV"], answer: 1 },
            { q: "Which empire occupied central Hungary for 150 years during the 16th and 17th centuries?", options: ["Roman Empire", "Austrian Empire", "Russian Empire", "Ottoman Empire"], answer: 3 },
            { q: "When did Hungary's first commercial railway line open?", options: ["1846", "1856", "1866", "1876"], answer: 0 },
            { q: "What is the name of the historic spa district in Budapest known for its thermal waters?", options: ["Margaret Island", "Rác baths", "Gellért Hill", "Obuda baths"], answer: 1 }
        ],
        hard: [
            { q: "Who was the Prime Minister whose 'Őszöd speech' leaked in 2006, causing massive protests?", options: ["Gordon Bajnai", "Péter Medgyessy", "Ferenc Gyurcsány", "Viktor Orbán"], answer: 2 },
            { q: "In what year did Hungary adopt its current Fundamental Law (constitution)?", options: ["1989", "1995", "2011", "2018"], answer: 2 },
            { q: "Which empire did Hungary share a dual monarchy with until 1918?", options: ["Ottoman Empire", "Russian Empire", "Austrian Empire", "German Empire"], answer: 2 },
            { q: "Who was the leader of the Hungarian Revolution of 1848?", options: ["Lajos Kossuth", "István Széchenyi", "Ferenc Deák", "Sándor Petőfi"], answer: 0 },
            { q: "What was the political ideology of the Arrow Cross Party during WWII?", options: ["Communist", "Liberal", "Fascist", "Social Democratic"], answer: 2 },
            { q: "Who was the communist leader of Hungary from 1956 to 1988?", options: ["Mátyás Rákosi", "János Kádár", "Imre Nagy", "Ernő Gerő"], answer: 1 },
            { q: "Which Hungarian politician became a prominent opposition figure in 2024, founding the TISZA party?", options: ["Gergely Karácsony", "Péter Magyar", "Anna Donáth", "Klára Dobrev"], answer: 1 },
            { q: "What is the term limit for the President of Hungary?", options: ["One 5-year term", "Two 5-year terms", "Two 4-year terms", "No term limits"], answer: 1 },
            { q: "Which institution is responsible for constitutional review in Hungary?", options: ["The Supreme Court (Kúria)", "The Constitutional Court", "The National Assembly", "The President"], answer: 1 },
            { q: "What was the 'Goulash Communism'?", options: ["A period of severe rationing", "A relatively liberal and prosperous form of communism under Kádár", "A communist agricultural policy", "A Soviet invasion strategy"], answer: 1 },
            { q: "In what year did the massive Hungarian civic and military revolution against the Habsburg Empire begin?", options: ["1848", "1867", "1914", "1956"], answer: 0 },
            { q: "Which Hungarian-born physicist is famously known as the 'father of the hydrogen bomb'?", options: ["Albert Einstein", "Leó Szilárd", "Eugene Wigner", "Edward Teller"], answer: 3 },
            { q: "What is the name of the mythical bird of prey in ancient Hungarian mythology?", options: ["Phoenix", "Griffin", "Turul", "Thunderbird"], answer: 2 },
            { q: "The infamous 'Blood in the Water' match at the 1956 Olympics was played in which sport?", options: ["Ice Hockey", "Water Polo", "Football", "Fencing"], answer: 1 },
            { q: "What is the largest recognized minority ethnic group in Hungary today?", options: ["German", "Slovak", "Romani", "Romanian"], answer: 2 },
            { q: "Which law passed in 1993 and caused diplomatic tensions by expanding Hungarians' rights beyond the country's borders?", options: ["The Minorities Protection Act", "The Status Law", "The Diaspora Act", "The Border Rights Act"], answer: 1 },
            { q: "What is the name of the Hungarian Nobel Prize in Literature recipient who fled to Switzerland during the 1956 revolution?", options: ["Imre Madách", "Péter Esterházy", "Sándor Márai", "György Lukács"], answer: 2 }
        ],
        expert: [
            { q: "What was the 'System of National Cooperation' (NER) declared by Fidesz in 2010?", options: ["A new economic plan", "A political declaration marking a new era after their two-thirds majority win", "A military alliance", "A treaty with neighboring countries"], answer: 1 },
            { q: "Which act passed in 2018 controversially centralized control over media outlets in a single foundation?", options: ["KESMA", "MTVA", "NMHH", "RTL Klub Act"], answer: 0 },
            { q: "In 1920, the Treaty of Trianon reduced Hungary's land area by approximately what percentage?", options: ["30%", "50%", "72%", "90%"], answer: 2 },
            { q: "Who served as Regent of the Kingdom of Hungary from 1920 to 1944?", options: ["Charles IV", "Miklós Horthy", "István Bethlen", "Pál Teleki"], answer: 1 },
            { q: "Which article of the EU treaty was triggered against Hungary in 2018 regarding the rule of law?", options: ["Article 7", "Article 50", "Article 11", "Article 2"], answer: 0 },
            { q: "The 'Stop Soros' laws passed in 2018 primarily targeted what?", options: ["Foreign currency loans", "NGOs assisting asylum seekers", "University funding", "Media ownership"], answer: 1 },
            { q: "What is the name of the highest judicial body in Hungary for civil and criminal matters?", options: ["Constitutional Court", "Kúria", "High Court of Justice", "Tribunal"], answer: 1 },
            { q: "Which Prime Minister was executed after the 1956 revolution?", options: ["János Kádár", "Mátyás Rákosi", "Imre Nagy", "Pál Maléter"], answer: 2 },
            { q: "Which electoral reform did Fidesz introduce prior to the 2014 elections?", options: ["Shift to pure PR", "Reduction of parliament size from 386 to 199 and gerrymandering", "Lowering voting age to 16", "Mandatory voting"], answer: 1 },
            { q: "Who was the 'Greatest Hungarian', a key figure in the 19th-century reform era?", options: ["Lajos Kossuth", "István Széchenyi", "Ferenc Deák", "Sándor Petőfi"], answer: 1 },
            { q: "What was the name of the short-lived communist state established in Hungary in 1919?", options: ["People's Republic of Hungary", "Hungarian Soviet Republic", "Democratic Republic of Hungary", "Hungarian Socialist Workers' State"], answer: 1 },
            { q: "Which brilliant Hungarian-American polymath made foundational contributions to game theory and the Manhattan Project?", options: ["John von Neumann", "Paul Erdős", "Theodore von Kármán", "Ignaz Semmelweis"], answer: 0 },
            { q: "What is the traditional pre-Christian Hungarian alphabet often referred to as?", options: ["Cyrillic", "Glagolitic", "Székely-Hungarian Rovás", "Ogham"], answer: 2 },
            { q: "Which devastating 1526 battle against the Ottomans effectively ended the independent Kingdom of Hungary?", options: ["Battle of Vienna", "Battle of Buda", "Battle of Mohács", "Battle of Eger"], answer: 2 },
            { q: "What is the Hungarian name for the historical region of Transylvania?", options: ["Felvidék", "Erdély", "Kárpátalja", "Délvidék"], answer: 1 },
            { q: "Which major constitutional amendment in 1997 strengthened the role of the Constitutional Court?", options: ["Amendment 31", "Amendment 42", "Amendment 19", "Amendment 55"], answer: 2 },
            { q: "Who was the mentor figure in the 2018-2024 opposition political revival against Fidesz?", options: ["Gábor Vona", "Péter Jakab", "László Tőkés", "János Áder"], answer: 2 }
        ]
    },
    romania: {
        easy: [
            { q: "What is the capital of Romania?", options: ["Sofia", "Budapest", "Bucharest", "Belgrade"], answer: 2 },
            { q: "What colors are on the Romanian flag?", options: ["Blue, Yellow, Red", "Red, White, Green", "Blue, White, Red", "Black, Yellow, Red"], answer: 0 },
            { q: "What is the official currency of Romania?", options: ["Euro", "Romanian Leu", "Forint", "Lev"], answer: 1 },
            { q: "Is Romania a member of the European Union?", options: ["Yes", "No", "Applying", "Suspended"], answer: 0 },
            { q: "Who was the dictator overthrown in the 1989 Romanian Revolution?", options: ["Todor Zhivkov", "Josip Broz Tito", "Nicolae Ceaușescu", "Enver Hoxha"], answer: 2 },
            { q: "Which famous region in Romania is associated with the Dracula legend?", options: ["Moldavia", "Wallachia", "Transylvania", "Dobruja"], answer: 2 },
            { q: "What language is primarily spoken in Romania?", options: ["Slavic", "Romanian", "Hungarian", "Russian"], answer: 1 },
            { q: "What type of government does Romania have?", options: ["Constitutional Monarchy", "Semi-presidential Republic", "Absolute Monarchy", "Federal Republic"], answer: 1 },
            { q: "What is the name of the massive parliament building in Bucharest?", options: ["The White House", "Palace of the Parliament", "People's Palace", "National Assembly Hall"], answer: 1 },
            { q: "Which body of water borders Romania to the east?", options: ["Mediterranean Sea", "Adriatic Sea", "Black Sea", "Caspian Sea"], answer: 2 },
            { q: "Which river forms much of the southern border between Romania and Bulgaria?", options: ["Rhine", "Danube", "Volga", "Elbe"], answer: 1 },
            { q: "What are the famous mountains that run through Romania?", options: ["Alps", "Carpathians", "Pyrenees", "Ural"], answer: 1 },
            { q: "What is the traditional Romanian dish of stuffed cabbage rolls called?", options: ["Sarmale", "Mici", "Mămăligă", "Ciorbă"], answer: 0 },
            { q: "What is the most widely practiced religion in Romania?", options: ["Catholicism", "Islam", "Eastern Orthodoxy", "Protestantism"], answer: 2 },
            { q: "Which legendary vampire is commonly associated with the Transylvania region?", options: ["Nosferatu", "Dracula", "Lestat", "Edward"], answer: 1 }
        ],
        medium: [
            { q: "When did Romania join the European Union?", options: ["2004", "2007", "2013", "1999"], answer: 1 },
            { q: "Who is the current President of Romania? (as of 2024)", options: ["Klaus Iohannis", "Traian Băsescu", "Ion Iliescu", "Marcel Ciolacu"], answer: 0 },
            { q: "What are the two chambers of the Romanian Parliament?", options: ["House of Commons and Lords", "Senate and Chamber of Deputies", "National Assembly and Senate", "Diet and Council"], answer: 1 },
            { q: "Which political party is traditionally considered the main center-left party in Romania?", options: ["PNL", "PSD", "USR", "AUR"], answer: 1 },
            { q: "When did Romania join NATO?", options: ["1999", "2004", "2007", "2010"], answer: 1 },
            { q: "Who was the first President of post-communist Romania?", options: ["Emil Constantinescu", "Ion Iliescu", "Traian Băsescu", "Petre Roman"], answer: 1 },
            { q: "The 'Colectiv nightclub fire' in 2015 led to the resignation of which Prime Minister?", options: ["Victor Ponta", "Dacian Cioloș", "Sorin Grindeanu", "Ludovic Orban"], answer: 0 },
            { q: "Which party is known as the main center-right liberal party in Romania?", options: ["PSD", "PNL", "UDMR", "AUR"], answer: 1 },
            { q: "What is the term length for the President of Romania?", options: ["4 years", "5 years", "6 years", "7 years"], answer: 1 },
            { q: "Which region united with Romania on December 1, 1918 (Great Union Day)?", options: ["Moldavia", "Wallachia", "Transylvania", "Bessarabia"], answer: 2 },
            { q: "Which Romanian gymnast scored the first perfect 10 in Olympic history in 1976?", options: ["Nadia Comăneci", "Simona Halep", "Gabriela Szabo", "Cătălina Ponor"], answer: 0 },
            { q: "What was the name of the ancient kingdom located roughly in present-day Romania?", options: ["Thrace", "Gaul", "Dacia", "Illyria"], answer: 2 },
            { q: "Which well-known budget car brand originates from Romania?", options: ["Skoda", "Lada", "Dacia", "Yugo"], answer: 2 },
            { q: "Which Romanian playwright is famous for absurd plays like 'The Bald Soprano'?", options: ["Mircea Eliade", "Eugène Ionesco", "Emil Cioran", "Tristan Tzara"], answer: 1 },
            { q: "What is the name of the traditional, highly embroidered Romanian folk blouse?", options: ["Ie", "Kilt", "Dirndl", "Sari"], answer: 0 }
        ],
        hard: [
            { q: "Which anti-corruption agency gained international recognition in Romania during the 2010s?", options: ["DIICOT", "DNA (National Anticorruption Directorate)", "ANI", "SRI"], answer: 1 },
            { q: "Who was the King of Romania forced to abdicate by the communists in 1947?", options: ["Ferdinand I", "Carol II", "Michael I", "Carol I"], answer: 2 },
            { q: "Which nationalist, right-wing populist party gained significant traction in the 2020 elections?", options: ["USR", "PNL", "AUR", "PRO Romania"], answer: 2 },
            { q: "In 2017, massive protests erupted in Romania against Ordinance 13. What did this ordinance attempt to do?", options: ["Increase taxes", "Decriminalize certain corruption offenses", "Ban protests", "Leave the EU"], answer: 1 },
            { q: "Who was the head of the DNA who was dismissed in 2018 and later became the first European Chief Prosecutor?", options: ["Laura Codruța Kövesi", "Monica Macovei", "Alina Bica", "Viorica Dăncilă"], answer: 0 },
            { q: "What is the 'UDMR' in Romanian politics?", options: ["The green party", "The Democratic Alliance of Hungarians in Romania", "A socialist union", "A far-right coalition"], answer: 1 },
            { q: "Who served as Romania's first female Prime Minister?", options: ["Viorica Dăncilă", "Elena Udrea", "Ana Pauker", "Carmen Dan"], answer: 0 },
            { q: "Which historic region joined Romania in 1859 under Alexandru Ioan Cuza?", options: ["Wallachia and Moldavia", "Transylvania and Banat", "Bessarabia and Bukovina", "Dobruja and Oltenia"], answer: 0 },
            { q: "What was the 'Securitate'?", options: ["The communist secret police", "The national bank", "The royal guard", "A political party"], answer: 0 },
            { q: "During which war did Romania initially fight for the Axis before switching to the Allies in 1944?", options: ["World War I", "World War II", "The Balkan Wars", "The Cold War"], answer: 1 },
            { q: "Who is widely considered the national poet of Romania?", options: ["Tudor Arghezi", "Lucian Blaga", "Mihai Eminescu", "George Coșbuc"], answer: 2 },
            { q: "In what year did Romania formally declare its independence from the Ottoman Empire?", options: ["1848", "1859", "1877", "1918"], answer: 2 },
            { q: "What is the name of the spectacular, winding mountain road built during Ceaușescu's rule?", options: ["Transalpina", "Transfăgărășan", "Bucegi Pass", "Olt Valley Road"], answer: 1 },
            { q: "Which renowned Romanian sculptor created 'The Endless Column' in Târgu Jiu?", options: ["Constantin Brâncuși", "Dimitrie Paciurea", "Ion Jalea", "Oscar Han"], answer: 0 },
            { q: "Which prominent Romanian-born philosopher wrote the pessimistic essay collection 'The Trouble with Being Born'?", options: ["Mircea Eliade", "Emil Cioran", "Lucian Blaga", "Nae Ionescu"], answer: 1 }
        ],
        expert: [
            { q: "Which Prime Minister led the technocratic government from 2015 to 2017?", options: ["Dacian Cioloș", "Florin Cîțu", "Mihai Tudose", "Nicolae Ciucă"], answer: 0 },
            { q: "The 'Mineriads' (Mineriade) in the early 1990s involved miners traveling to Bucharest to do what?", options: ["Strike for better wages", "Violently suppress anti-government protests", "Build the Palace of the Parliament", "Overthrow the President"], answer: 1 },
            { q: "Who was the fascist leader (Conducător) of Romania during much of WWII?", options: ["Corneliu Zelea Codreanu", "Horia Sima", "Ion Antonescu", "King Carol II"], answer: 2 },
            { q: "What is the threshold to enter the Romanian Parliament?", options: ["3%", "5%", "7%", "10%"], answer: 1 },
            { q: "In 2012, there was a controversial political crisis involving an attempt to impeach which President?", options: ["Ion Iliescu", "Klaus Iohannis", "Traian Băsescu", "Emil Constantinescu"], answer: 2 },
            { q: "Which political alliance formed between the bitter rivals PNL and PSD in 2021?", options: ["USL (Social Liberal Union)", "National Coalition for Romania (CNR)", "Alliance 2020", "Democratic Convention"], answer: 1 },
            { q: "What was the 'Snagov Declaration' of 1995?", options: ["A treaty with Hungary", "A consensus among parties for Euro-Atlantic integration", "A declaration of independence", "A communist manifesto"], answer: 1 },
            { q: "Which party was founded by Nicușor Dan and later merged to become USR?", options: ["Save Bucharest Union (USB)", "M10", "PLUS", "DEMOS"], answer: 0 },
            { q: "Which Constitutional Court decision in 2018 severely limited the President's power regarding the dismissal of chief prosecutors?", options: ["Decision 358", "Decision 611", "Decision 1", "Decision 400"], answer: 0 },
            { q: "Who led the far-right Iron Guard movement in the interwar period before his assassination in 1938?", options: ["Ion Antonescu", "Horia Sima", "Corneliu Zelea Codreanu", "Octavian Goga"], answer: 2 },
            { q: "Which Romanian scientist discovered pancreine (insulin) but was omitted from the Nobel Prize?", options: ["Henri Coandă", "Nicolae Paulescu", "Victor Babeș", "Emil Palade"], answer: 1 },
            { q: "The devastating Battle of Mărășești in WWI was fought under which famous Romanian rallying cry?", options: ["Deșteaptă-te, române!", "Pe aici nu se trece!", "Nihil Sine Deo", "Vrem să ne unim cu Țara!"], answer: 1 },
            { q: "What was the name of the influential interwar cultural movement centered around traditional Romanian values?", options: ["Sămănătorism", "Junimea", "Gândirism", "Poporanism"], answer: 2 },
            { q: "Which ancient Dacian king fought two major wars against the Roman Emperor Trajan before committing suicide?", options: ["Burebista", "Decebalus", "Scorylo", "Cotiso"], answer: 1 },
            { q: "Who directed 'Scurtă Istorie' (A Short History), winning the 1957 Palme d'Or for best short film?", options: ["Ion Popescu-Gopo", "Sergiu Nicolaescu", "Liviu Ciulei", "Lucian Pintilie"], answer: 0 }
        ]
    },
    trains: {
        easy: [
            { q: "What does 'TGV' stand for in French high-speed rail?", options: ["Train à Grande Vitesse", "Transport Général Rapide", "Train Géant Rapide", "Transit Grand Vitesse"], answer: 0 },
            { q: "Which country is famous for its 'Shinkansen' or bullet trains?", options: ["China", "Japan", "South Korea", "Germany"], answer: 1 },
            { q: "What goes under the English Channel to connect the UK and France?", options: ["The Channel Tunnel (Eurotunnel)", "The North Sea Bridge", "The Atlantic Tube", "The Britannia Tunnel"], answer: 0 },
            { q: "What power source drove the earliest trains?", options: ["Electricity", "Diesel", "Steam", "Solar"], answer: 2 },
            { q: "Which famous fictional train takes students to Hogwarts?", options: ["The Polar Express", "The Orient Express", "The Hogwarts Express", "The Flying Scotsman"], answer: 2 },
            { q: "What are the tracks that trains run on primarily made of?", options: ["Wood", "Steel", "Aluminum", "Concrete"], answer: 1 },
            { q: "What do you call the person who drives a train?", options: ["Captain", "Pilot", "Engineer / Driver", "Conductor"], answer: 2 },
            { q: "Which vehicle is typically found at the back of an old American freight train?", options: ["Locomotive", "Caboose", "Dining Car", "Sleeper"], answer: 1 },
            { q: "What is the London underground railway system commonly called?", options: ["The Tube", "The Metro", "The Subway", "The U-Bahn"], answer: 0 },
            { q: "What is a train that carries goods rather than passengers called?", options: ["Commuter train", "Light rail", "Freight train", "Monorail"], answer: 2 },
            { q: "What sound is traditionally associated with a steam train's whistle?", options: ["Beep beep", "Honk honk", "Choo choo", "Ding ding"], answer: 2 },
            { q: "What is the front car of a train that provides the power called?", options: ["Caboose", "Carriage", "Locomotive", "Tender"], answer: 2 },
            { q: "Which famous children's character is a small, cheeky blue tank engine?", options: ["Percy", "Gordon", "Thomas", "James"], answer: 2 },
            { q: "What do trains run on?", options: ["Asphalt", "Dirt roads", "Railway tracks", "Water"], answer: 2 },
            { q: "Where do passengers typically wait to board a train?", options: ["Runway", "Platform", "Dock", "Pier"], answer: 1 }
        ],
        medium: [
            { q: "Which country has the longest high-speed railway network in the world?", options: ["Japan", "France", "China", "Spain"], answer: 2 },
            { q: "What is the longest continuous railway line in the world?", options: ["Trans-Siberian Railway", "Union Pacific Railroad", "Indian Pacific", "Canadian National"], answer: 0 },
            { q: "Which famous luxury train originally ran from Paris to Istanbul?", options: ["The Flying Scotsman", "The Orient Express", "The Blue Train", "The Ghan"], answer: 1 },
            { q: "What does 'Maglev' stand for?", options: ["Magnetic Levitation", "Magnitude Level", "Magnified Lever", "Magnetic Locomotive"], answer: 0 },
            { q: "In the context of railways, what is a 'gauge'?", options: ["The speed limit", "The distance between the inner faces of the two rails", "The weight of the train", "The length of the track"], answer: 1 },
            { q: "Which city has the oldest underground railway network in the world?", options: ["New York", "Paris", "London", "Budapest"], answer: 2 },
            { q: "What is the 'Flying Scotsman'?", options: ["A famous British steam locomotive", "A modern jet", "A Scottish train operator", "A hovercraft"], answer: 0 },
            { q: "Which country operates the ICE (Intercity Express) high-speed trains?", options: ["Italy", "Germany", "Switzerland", "Austria"], answer: 1 },
            { q: "What technology allows trains to lean into curves to maintain higher speeds?", options: ["Maglev", "Tilting train technology", "Articulated bogeys", "Air suspension"], answer: 1 },
            { q: "What is the name of the high-speed rail service connecting major cities in the US Northeast Corridor?", options: ["Acela", "Silver Meteor", "Empire Builder", "Coast Starlight"], answer: 0 },
            { q: "How are most modern high-speed trains in Europe and Japan powered?", options: ["Diesel", "Steam", "Electricity via overhead lines", "Battery power"], answer: 2 },
            { q: "Which famous luxury tourist train route winds through the spectacular Canadian Rockies?", options: ["The Canadian", "Rocky Mountaineer", "The Ocean", "Polar Bear Express"], answer: 1 },
            { q: "What is the massive underground public transit system in New York City commonly called?", options: ["The Tube", "The Metro", "The Subway", "The L"], answer: 2 },
            { q: "Which fictional train takes Katniss and Peeta from District 12 to the Capitol?", options: ["The Tribute Train", "The Panem Express", "The Capitol Crawler", "The Hunger Rail"], answer: 0 },
            { q: "What is a monorail?", options: ["A train with one wheel", "A train that runs on a single continuous rail", "A train that only goes in one direction", "A train driven by one person"], answer: 1 }
        ],
        hard: [
            { q: "Who built the first successful working steam locomotive in 1804?", options: ["George Stephenson", "James Watt", "Richard Trevithick", "Isambard Kingdom Brunel"], answer: 2 },
            { q: "What is 'Standard Gauge'?", options: ["1,000 mm", "1,435 mm (4 ft 8 1⁄2 in)", "1,524 mm (5 ft)", "1,676 mm (5 ft 6 in)"], answer: 1 },
            { q: "Which commercial Maglev train system is currently the fastest in regular operation, reaching 431 km/h?", options: ["Chuo Shinkansen", "Shanghai Maglev Train", "Incheon Airport Maglev", "Linimo"], answer: 1 },
            { q: "What was the name of George Stephenson's famous steam locomotive that won the Rainhill Trials in 1829?", options: ["The Rocket", "The Mallard", "The Iron Horse", "The Puffing Billy"], answer: 0 },
            { q: "Which steam locomotive holds the official world speed record for steam traction at 126 mph (203 km/h)?", options: ["Flying Scotsman", "Mallard", "Union Pacific Big Boy", "Fairy Queen"], answer: 1 },
            { q: "What does 'ERTMS' stand for in European rail signaling?", options: ["European Rail Traffic Management System", "Electronic Railway Transit Management System", "European Rapid Train Movement System", "Electric Rail Transit Monitoring System"], answer: 0 },
            { q: "Which country's high-speed rail is known as 'AVE'?", options: ["Italy", "Spain", "Portugal", "Argentina"], answer: 1 },
            { q: "What is an 'Articulated Locomotive'?", options: ["A locomotive with a jointed frame to allow it to negotiate sharp curves", "A train with connected passenger cars sharing bogies", "An electric locomotive", "A diesel-hydraulic locomotive"], answer: 0 },
            { q: "The 'Golden Spike' marking the completion of the First Transcontinental Railroad in the US was driven in which state?", options: ["California", "Nevada", "Utah", "Wyoming"], answer: 2 },
            { q: "Which mountain range is crossed by the famous Bernina Express?", options: ["The Pyrenees", "The Alps", "The Andes", "The Rockies"], answer: 1 },
            { q: "The Darjeeling Himalayan Railway in India is affectionately known by what nickname?", options: ["The Mountain Goat", "The Tea Train", "The Toy Train", "The Cloud Climber"], answer: 2 },
            { q: "What is the standard track gauge used across the Russian railway network?", options: ["1435 mm", "1520 mm", "1676 mm", "1000 mm"], answer: 1 },
            { q: "Which infamous train robbery occurred in Buckinghamshire, UK in 1963?", options: ["The Midnight Heist", "The Royal Mail Robbery", "The Great Train Robbery", "The Buckingham Job"], answer: 2 },
            { q: "What is the steepest rack railway in the world, located in Switzerland?", options: ["Pilatus Railway", "Jungfrau Railway", "Gornergrat Railway", "Rigi Railways"], answer: 0 },
            { q: "Which Japanese railway company operates the famous Tokaido Shinkansen line?", options: ["JR East", "JR West", "JR Central", "Tokyo Metro"], answer: 2 }
        ],
        expert: [
            { q: "The 'Broad Gauge' promoted by Isambard Kingdom Brunel in the UK was how wide?", options: ["1,676 mm (5 ft 6 in)", "1,829 mm (6 ft)", "2,140 mm (7 ft 0 1⁄4 in)", "1,524 mm (5 ft)"], answer: 2 },
            { q: "What is the name of the coupling mechanism universally used on North American freight cars?", options: ["Scharfenberg coupler", "Janney (knuckle) coupler", "Buffer and chain", "Buckeye coupler"], answer: 1 },
            { q: "The L0 Series Maglev in Japan holds the absolute world railway speed record. What speed did it achieve in 2015?", options: ["581 km/h (361 mph)", "603 km/h (375 mph)", "632 km/h (393 mph)", "680 km/h (423 mph)"], answer: 1 },
            { q: "What is a 'Funicular' railway?", options: ["A railway using a rack and pinion", "A cable railway on a steep incline where counterbalanced cars move up and down", "A suspended monorail", "A train powered by compressed air"], answer: 1 },
            { q: "Which famous railway engineer designed the Great Western Railway in the UK?", options: ["George Stephenson", "Robert Stephenson", "Isambard Kingdom Brunel", "Nigel Gresley"], answer: 2 },
            { q: "What type of braking system was invented by George Westinghouse and revolutionized train safety?", options: ["Dynamic braking", "Vacuum brakes", "Air brakes", "Electromagnetic brakes"], answer: 2 },
            { q: "In signal engineering, what does 'CBTC' stand for?", options: ["Computer Based Train Control", "Communications-Based Train Control", "Centralised Block Traffic Control", "Coordinated Braking and Tracking Control"], answer: 1 },
            { q: "The Darjeeling Himalayan Railway in India uses which narrow gauge?", options: ["1,000 mm (Metre gauge)", "762 mm (2 ft 6 in)", "610 mm (2 ft)", "800 mm"], answer: 2 },
            { q: "What is a 'Pantograph'?", options: ["A track switching device", "The apparatus on the roof of an electric train that collects power from an overhead wire", "A type of steam valve", "A device for coupling carriages"], answer: 1 },
            { q: "Which locomotive, built by ALCO, holds the record for the largest and most powerful steam locomotive ever built?", options: ["Pennsylvania Railroad T1", "New York Central Hudson", "Union Pacific Big Boy", "Norfolk and Western J Class"], answer: 2 },
            { q: "The 'Wuppertal Schwebebahn' in Germany is famous for being what type of unique railway?", options: ["A funicular", "A suspended monorail", "A magnetic levitation train", "A rack-and-pinion railway"], answer: 1 },
            { q: "Which specific class of steam locomotive was the famous speed-record-holder 'Mallard'?", options: ["LMS Princess Coronation Class", "GWR Castle Class", "SR Merchant Navy Class", "LNER Class A4"], answer: 3 },
            { q: "In railway terminology, what does the term 'consist' refer to?", options: ["The speed limit of a track section", "The lineup of individual vehicles making up a train", "The maintenance schedule", "The signal interlocking system"], answer: 1 },
            { q: "The famous 'Ghan' train in Australia is named in honor of camel drivers from which country?", options: ["India", "Egypt", "Afghanistan", "Saudi Arabia"], answer: 2 },
            { q: "What is the primary purpose of a 'catch point' or 'derail' on a railway line?", options: ["To switch tracks smoothly", "To intentionally derail runaway or unauthorized trains to prevent worse collisions", "To catch mailbags on the fly", "To provide an emergency braking surface"], answer: 1 }
        ]
    },
    personal: [
        { q: "When is Radu's birthday?", options: ["18th March 1998", "19th March 1998", "18th March 1999", "19th March 1974"], answer: 1 },
        { q: "What pet did Radu never have?", options: ["Bunny", "Cat", "Rat", "Dog"], answer: 0 },
        { q: "How tall is he? Exact passport cm measurement", options: ["180cm", "182cm", "181cm", "Tall Enough"], answer: 2 },
        { q: "What is his comfort food?", options: ["Pineapple Pizza", "Langos", "Loaded Fries with Feta", "Pasta Carbonara"], answer: 2 },
        { q: "How many push-ups can he do at this time?", options: ["0-5", "5-15", "15-25", "25+"], answer: 3 },
        { q: "What is Radu's alter ego rapper name?", options: ["Lil Gipsy", "Lil Trans (short for Transylvanian)", "Lil Dicky", "Lil Owl"], answer: 3 },
        { q: "Which of these countries has Radu never been to?", options: ["Moldova", "Spain", "China", "Vietnam"], answer: 0 },
        { q: "Why did Radu loose his hair?", options: ["Too much testosterone", "So other guys can have a chance", "All true Romanians are bald", "He is Hairphobic"], answer: 1 },
        { q: "What was Radu's pet rat's name?", options: ["Lipo", "Mipo", "Dipo", "Bipo"], answer: 3 },
        { q: "What does Radu love more than anything in the world?", options: ["His Motorcycle", "Blacky", "Eating food", "Bianka"], answer: 3 }
    ]
};

const qotdData = [
    { category: "Otters", q: "What is a group of resting otters called?", options: ["A raft", "A flock", "A herd", "A school"], answer: 0 },
    { category: "Hungary", q: "What is the largest lake in Hungary?", options: ["Lake Tisza", "Lake Balaton", "Lake Velence", "Lake Fertő"], answer: 1 },
    { category: "Food related", q: "Which of these is a traditional Hungarian stew?", options: ["Paella", "Goulash", "Ratatouille", "Moussaka"], answer: 1 },
    { category: "Romania", q: "What is the second largest city in Romania by population?", options: ["Timișoara", "Iași", "Cluj-Napoca", "Constanța"], answer: 2 },
    { category: "Politics", q: "In what year was the United Nations established?", options: ["1918", "1939", "1945", "1955"], answer: 2 },
    { category: "Salsa", q: "Salsa music and dance originated primarily in which city?", options: ["Havana", "San Juan", "New York City", "Miami"], answer: 2 },
    { category: "Hungarian politics", q: "Who was the first democratically elected Prime Minister of Hungary after the fall of communism?", options: ["József Antall", "Gyula Horn", "Viktor Orbán", "Péter Medgyessy"], answer: 0 },
    { category: "Interesting history", q: "How long did the shortest war in history (Anglo-Zanzibar War) last?", options: ["38 minutes", "2 days", "3 hours", "1 week"], answer: 0 },
    { category: "Trains", q: "Which country has the oldest operational railway in the world?", options: ["France", "USA", "Germany", "United Kingdom"], answer: 3 },
    { category: "Otters", q: "Which species of otter is the heaviest?", options: ["North American River Otter", "Sea Otter", "Giant Otter", "Asian Small-clawed Otter"], answer: 1 },
    { category: "Food related", q: "What is the main ingredient in traditional Romanian Mămăligă?", options: ["Wheat flour", "Potato", "Cornmeal", "Rice"], answer: 2 },
    { category: "Salsa", q: "Which instrument is considered the core rhythmic foundation of Salsa music?", options: ["Congas", "Clave", "Bongos", "Trumpet"], answer: 1 },
    { category: "Geography", q: "Which is the smallest country in the world by area?", options: ["Monaco", "Liechtenstein", "Vatican City", "San Marino"], answer: 2 },
    { category: "European Union", q: "In what year did the European Union officially adopt the Euro as its currency?", options: ["1999", "2001", "2002", "2004"], answer: 2 },
    { category: "Trains", q: "What does ICE stand for in German high-speed rail?", options: ["International City Express", "InterCityExpress", "Intercontinental Electric", "Inter-European Connection"], answer: 1 },
    { category: "Hungarian culture", q: "What is Tokaji, for which the Hungarian region is famous?", options: ["A traditional dance", "A type of wine", "A folk costume", "A musical instrument"], answer: 1 },
    { category: "Nature", q: "How long can otters hold their breath underwater?", options: ["Up to 30 seconds", "Up to 2 minutes", "Up to 8 minutes", "Up to 15 minutes"], answer: 2 }
];
